"""Adding field in table lb_libro to store csv files path

Revision ID: 093523faa9a1
Revises: 
Create Date: 2018-12-04 20:03:34.037838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '093523faa9a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lb_libro', sa.Column('li_keywords_csv', sa.Text, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lb_libro', 'li_keywords_csv')    
    # ### end Alembic commands ###
